export const data = [
  {
    name: "Adrar",
    wilayaNumber: 1,
    lat: 27.8742,
    long: 0.2833,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "Chlef",
    wilayaNumber: 2,
    lat: 36.1656,
    long: 1.3361,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Laghouat",
    wilayaNumber: 3,
    lat: 33.8116,
    long: 2.8809,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Oum el Bouaghi",
    wilayaNumber: 4,
    lat: 35.8667,
    long: 7.1,
    deliveryFees: "SHORT_DISTANCE",
  },
  {
    name: "Batna",
    wilayaNumber: 5,
    lat: 35.5513,
    long: 6.1761,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Béjaïa",
    wilayaNumber: 6,
    lat: 36.7475,
    long: 5.0645,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Biskra",
    wilayaNumber: 7,
    lat: 34.85,
    long: 5.73,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Béchar",
    wilayaNumber: 8,
    lat: 31.6167,
    long: 2.2167,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "Blida",
    wilayaNumber: 9,
    lat: 36.4816,
    long: 2.8388,
    deliveryFees: "SHORT_DISTANCE",
  },
  {
    name: "Bouira",
    wilayaNumber: 10,
    lat: 36.365,
    long: 3.9,
    deliveryFees: "SHORT_DISTANCE",
  },
  {
    name: "Tamanrasset",
    wilayaNumber: 11,
    lat: 22.785,
    long: 5.5228,
    deliveryFees: "EXPRESS",
  },
  {
    name: "Tébessa",
    wilayaNumber: 12,
    lat: 35.4042,
    long: 8.1247,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Tlemcen",
    wilayaNumber: 13,
    lat: 34.8783,
    long: 1.3187,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Tiaret",
    wilayaNumber: 14,
    lat: 35.3782,
    long: 1.3151,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Tizi Ouzou",
    wilayaNumber: 15,
    lat: 36.7167,
    long: 4.05,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Alger",
    wilayaNumber: 16,
    lat: 36.7538,
    long: 3.0588,
    deliveryFees: "SHORT_DISTANCE",
  },
  {
    name: "Djelfa",
    wilayaNumber: 17,
    lat: 34.6667,
    long: 3.25,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Jijel",
    wilayaNumber: 18,
    lat: 36.8058,
    long: 5.7564,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Sétif",
    wilayaNumber: 19,
    lat: 36.19,
    long: 5.41,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Saïda",
    wilayaNumber: 20,
    lat: 34.8436,
    long: 0.145,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Skikda",
    wilayaNumber: 21,
    lat: 36.8796,
    long: 6.9094,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Sidi Bel Abbès",
    wilayaNumber: 22,
    lat: 35.1939,
    long: 0.6411,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Annaba",
    wilayaNumber: 23,
    lat: 36.8984,
    long: 7.7645,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Guelma",
    wilayaNumber: 24,
    lat: 36.4667,
    long: 7.4333,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Constantine",
    wilayaNumber: 25,
    lat: 36.365,
    long: 6.6147,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Medea",
    wilayaNumber: 26,
    lat: 36.2667,
    long: 2.75,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Mostaganem",
    wilayaNumber: 27,
    lat: 35.9383,
    long: 0.0894,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Msila",
    wilayaNumber: 28,
    lat: 35.7042,
    long: 4.5422,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Mascara",
    wilayaNumber: 29,
    lat: 35.4,
    long: 0.14,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Ouargla",
    wilayaNumber: 30,
    lat: 31.9461,
    long: 5.3219,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "Oran",
    wilayaNumber: 31,
    lat: 35.697,
    long: 0.6308,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "El Bayadh",
    wilayaNumber: 32,
    lat: 33.6936,
    long: 1.0167,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "Illizi",
    wilayaNumber: 33,
    lat: 26.4833,
    long: 8.4667,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "Bordj Bou Arréridj",
    wilayaNumber: 34,
    lat: 36.0733,
    long: 4.7639,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Boumerdes",
    wilayaNumber: 35,
    lat: 36.7594,
    long: 3.4764,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "El Tarf",
    wilayaNumber: 36,
    lat: 36.7678,
    long: 8.3131,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Tindouf",
    wilayaNumber: 37,
    lat: 27.6703,
    long: 8.1478,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "Tissemsilt",
    wilayaNumber: 38,
    lat: 35.6075,
    long: 1.8111,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "El Oued",
    wilayaNumber: 39,
    lat: 33.3632,
    long: 6.8478,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Khenchela",
    wilayaNumber: 40,
    lat: 35.4375,
    long: 7.1506,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Souk Ahras",
    wilayaNumber: 41,
    lat: 36.29,
    long: 7.95,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Tipaza",
    wilayaNumber: 42,
    lat: 36.5975,
    long: 2.45,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Mila",
    wilayaNumber: 43,
    lat: 36.45,
    long: 6.2667,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Aïn Defla",
    wilayaNumber: 44,
    lat: 36.2519,
    long: 1.9786,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Naama",
    wilayaNumber: 45,
    lat: 33.2667,
    long: 0.3167,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "Ain Temouchent",
    wilayaNumber: 46,
    lat: 35.3125,
    long: 1.1406,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Ghardaia",
    wilayaNumber: 47,
    lat: 32.4894,
    long: 3.6739,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Relizane",
    wilayaNumber: 48,
    lat: 35.7422,
    long: 0.5564,
    deliveryFees: "MEDIUM_DISTANCE",
  },
  {
    name: "Timimoun",
    wilayaNumber: 49,
    lat: 29.3333,
    long: 0.25,
    deliveryFees: "EXPRESS",
  },
  {
    name: "Bordj Badji Mokhtar",
    wilayaNumber: 50,
    lat: 23.760643,
    long: -0.9056623,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "Ouled Djellal",
    wilayaNumber: 51,
    lat: 34.4466834,
    long: 5.1015225,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "Béni Abbès",
    wilayaNumber: 52,
    lat: 30.1325,
    long: -2.1671,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "In Salah",
    wilayaNumber: 53,
    lat: 27.1928,
    long: 2.4852,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "In Guezzam",
    wilayaNumber: 54,
    lat: 19.5709,
    long: 5.7694,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "Touggourt",
    wilayaNumber: 55,
    lat: 33.1,
    long: 6.0667,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "Djanet",
    wilayaNumber: 56,
    lat: 24.5546,
    long: 9.4812,
    deliveryFees: "EXPRESS",
  },
  {
    name: "El M'Ghair",
    wilayaNumber: 57,
    lat: 33.9506,
    long: 5.9242,
    deliveryFees: "LONG_DISTANCE",
  },
  {
    name: "El Meniaa",
    wilayaNumber: 58,
    lat: 30.5833,
    long: 2.8833,
    deliveryFees: "LONG_DISTANCE",
  },
];
